version: '3.9'

services:
  app:
    build: .
    command: python -m librenms_mcp
    volumes:
      - .:/app
    environment:
      - LIBRENMS_API_URL=${LIBRENMS_API_URL}
      - LIBRENMS_API_TOKEN=${LIBRENMS_API_TOKEN}
    ports:
      - "8000:8000"
    profiles: ["dev"]

  app-prod:
    build: .
    command: python -m librenms_mcp
    environment:
      - LIBRENMS_API_URL=${LIBRENMS_API_URL}
      - LIBRENMS_API_TOKEN=${LIBRENMS_API_TOKEN}
    ports:
      - "8000:8000"
    profiles: ["prod"]
